services:
  - type: web
    name: chatbot
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: flask run
    pythonVersion: 3.10
